alpha = _{ 'a'..'z' | 'A'..'Z' }
digit = { '0'..'9' }

ident = { (alpha | digit)+ }

value = { "()" }

tp = { "1" | "0" }

def = { !digit ~ ident ~ " " ~ "=" ~ " " ~ value ~ " :" ~ ident ~ " [" ~ tp ~ "]" }

ws = _{ (" " | NEWLINE )+ }

apg = { "{" ~ ws ~ (def ~ ws)+ ~ "}" }

define = { ident ~ ws ~ ":=" ~ ws ~ apg }

plus = { ident ~ ws ~ ":=" ~ ws ~ ident ~ ws ~ "+" ~ ws ~ ident }

term = _{ define | plus }

apg_file = { SOI ~ ws? ~ (term ~ ws?)+ ~ EOI }